name: Test EasyBuild Setup Scripts

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-rocky9:
    name: Test on Rocky Linux 9
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
      options: --privileged
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run root bootstrap
        run: bash scripts/01_root_bootstrap.sh
      
      - name: Create test user
        run: |
          useradd -m testuser
          usermod -aG easybuildgrp testuser
          echo "testuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      
      - name: Run user bootstrap
        run: |
          su - testuser -c "cd $GITHUB_WORKSPACE && bash scripts/02_user_bootstrap.sh"
      
      - name: Verify installation
        run: |
          su - testuser -c "eb --version"
          su - testuser -c "eb --show-config"
          su - testuser -c "module avail"
      
      - name: Run test build
        run: |
          su - testuser -c "cd $GITHUB_WORKSPACE && bash scripts/03_build_example.sh"
        timeout-minutes: 30
      
      - name: Verify build results
        run: |
          test -d /opt/easybuild/software/GCCcore/13.2.0
          su - testuser -c "module spider GCCcore/13.2.0"
